# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sphere', [dirname(__file__)])
        except ImportError:
            import _sphere
            return _sphere
        if fp is not None:
            try:
                _mod = imp.load_module('_sphere', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sphere = swig_import_helper()
    del swig_import_helper
else:
    import _sphere
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Sphere(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Sphere, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Sphere, name)
    __repr__ = _swig_repr
    __swig_setmethods__["center"] = _sphere.Sphere_center_set
    __swig_getmethods__["center"] = _sphere.Sphere_center_get
    if _newclass:
        center = _swig_property(_sphere.Sphere_center_get, _sphere.Sphere_center_set)
    __swig_setmethods__["radius"] = _sphere.Sphere_radius_set
    __swig_getmethods__["radius"] = _sphere.Sphere_radius_get
    if _newclass:
        radius = _swig_property(_sphere.Sphere_radius_get, _sphere.Sphere_radius_set)
    __swig_setmethods__["refrac_idx"] = _sphere.Sphere_refrac_idx_set
    __swig_getmethods__["refrac_idx"] = _sphere.Sphere_refrac_idx_get
    if _newclass:
        refrac_idx = _swig_property(_sphere.Sphere_refrac_idx_get, _sphere.Sphere_refrac_idx_set)

    def __init__(self):
        this = _sphere.new_Sphere()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _sphere.delete_Sphere
    __del__ = lambda self: None
Sphere_swigregister = _sphere.Sphere_swigregister
Sphere_swigregister(Sphere)


def s_slice(arg1, arg2):
    return _sphere.s_slice(arg1, arg2)
s_slice = _sphere.s_slice

def s_new(arg1, arg2, arg3):
    return _sphere.s_new(arg1, arg2, arg3)
s_new = _sphere.s_new
# This file is compatible with both classic and new-style classes.


